services:

  bot:
    build: .
    container_name: flight-price-tracker-bot
    restart: unless-stopped

    env_file:
      - .env.docker

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    command: >
      sh -c "
      uv run alembic upgrade head &&
      uv run python -m app.main
      "


  postgres:
    image: postgres:17
    container_name: flight-price-tracker-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: flight_price_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Gfd33Sik$$kq"

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d flight_price_tracker"
        ]
      interval: 10s
      timeout: 5s
      retries: 5



  redis:
    image: redis:7-alpine
    container_name: flight-price-tracker-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 5



volumes:

  postgres_data:

  redis_data: