"""Add cascade delete for price history

Revision ID: 12c80c304f22
Revises: 6b6a208f3b7f
Create Date: 2026-07-17 20:05:46.435076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c80c304f22'
down_revision: Union[str, Sequence[str], None] = '6b6a208f3b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('price_history_track_id_fkey'), 'price_history', type_='foreignkey')
    op.create_foreign_key(None, 'price_history', 'tracks', ['track_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_history', type_='foreignkey')
    op.create_foreign_key(op.f('price_history_track_id_fkey'), 'price_history', 'tracks', ['track_id'], ['id'])
    # ### end Alembic commands ###
