"""Add no flights notification flag

Revision ID: 18eae089ade5
Revises: 12c80c304f22
Create Date: 2026-07-17 23:38:41.401562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18eae089ade5'
down_revision: Union[str, Sequence[str], None] = '12c80c304f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'tracks',
        sa.Column(
            'no_flights_notified',
            sa.Boolean(),
            nullable=True
        )
    )

    op.execute(
        """
        UPDATE tracks
        SET no_flights_notified = FALSE
        """
    )

    op.alter_column(
        'tracks',
        'no_flights_notified',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'no_flights_notified')
    # ### end Alembic commands ###
