"""Add target price to tracks

Revision ID: 48cf54dd6c93
Revises: b80273bd8bf3
Create Date: 2026-07-16 16:05:08.057184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48cf54dd6c93'
down_revision: Union[str, Sequence[str], None] = 'b80273bd8bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('target_price', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('last_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'last_price')
    op.drop_column('tracks', 'target_price')
    # ### end Alembic commands ###
