"""Remove provider from price history

Revision ID: 6b6a208f3b7f
Revises: 924ce4a425f2
Create Date: 2026-07-17 17:01:24.173733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6a208f3b7f'
down_revision: Union[str, Sequence[str], None] = '924ce4a425f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('price_history_provider_id_fkey'), 'price_history', type_='foreignkey')
    op.drop_column('price_history', 'provider_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history', sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('price_history_provider_id_fkey'), 'price_history', 'providers', ['provider_id'], ['id'])
    # ### end Alembic commands ###
